In [4]:
import numpy as np
def calc_entropy (P, base):
    logP = None
    if base == "2":
        logP = np.log2(P)
    elif base == "10":
        logP = np.log10(P)
    elif base == "e":
        logP = np.log(P)
    print P
    print logP
    print P*logP
    return -sum (P*logP)

In [5]:
P = (0.15, 0.2, 0.65)
calc_entropy(P, base="2")

(0.15, 0.2, 0.65)
[-2.73696559 -2.32192809 -0.62148838]
[-0.41054484 -0.46438562 -0.40396744]


1.278897902987479

In [6]:
P = (0.15, 0.2, 0.65)
calc_entropy(P, base="10")

(0.15, 0.2, 0.65)
[-0.82390874 -0.69897    -0.18708664]
[-0.12358631 -0.139794   -0.12160632]


0.38498663019099544

In [7]:
P = (0.15, 0.2, 0.65)
calc_entropy(P, base="e")

(0.15, 0.2, 0.65)
[-1.89711998 -1.60943791 -0.43078292]
[-0.284568   -0.32188758 -0.2800089 ]


0.88646447567979747